config/routes.rb
Rails.application.routes.draw do



  resources :fits do 
  	 resources :lits 
     resources :tits
  	end 

  resources :days do 
    resources :things 
    resources :kings


  end 

 


  get 'welcomes/home'

  resources :teams do 
    resources :players 
  end 

  root "welcomes#home"
  
end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :things 
	has_many :kings
end

app/models/fit.rb
class Fit < ActiveRecord::Base
	has_many :lits
	has_many :tits
end

app/models/king.rb
class King < ActiveRecord::Base
  belongs_to :day
end

app/models/lit.rb
class Lit < ActiveRecord::Base
  belongs_to :fit
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :players
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :day
end

app/models/tit.rb
class Tit < ActiveRecord::Base
  belongs_to :fit
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [ :show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.paginate(:page => params[:page], :per_page => 8).order('created_at DESC')
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render :new }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date)
    end
end

app/controllers/fits_controller.rb
class FitsController < ApplicationController
  before_action :set_fit, only: [:show, :edit, :update, :destroy]

  # GET /fits
  # GET /fits.json
  def index
    @fits = Fit.paginate(:page => params[:page], :per_page => 8).order('created_at DESC')
  end

  # GET /fits/1
  # GET /fits/1.json
  def show
  end

  # GET /fits/new
  def new
    @fit = Fit.new
  end

  # GET /fits/1/edit
  def edit
  end

  # POST /fits
  # POST /fits.json
  def create
    @fit = Fit.new(fit_params)

    respond_to do |format|
      if @fit.save
        format.html { redirect_to @fit, notice: 'Fit was successfully created.' }
        format.json { render :show, status: :created, location: @fit }
      else
        format.html { render :new }
        format.json { render json: @fit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fits/1
  # PATCH/PUT /fits/1.json
  def update
    respond_to do |format|
      if @fit.update(fit_params)
        format.html { redirect_to @fit, notice: 'Fit was successfully updated.' }
        format.json { render :show, status: :ok, location: @fit }
      else
        format.html { render :edit }
        format.json { render json: @fit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fits/1
  # DELETE /fits/1.json
  def destroy
    @fit.destroy
    respond_to do |format|
      format.html { redirect_to fits_url, notice: 'Fit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fit
      @fit = Fit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fit_params
      params.require(:fit).permit(:day)
    end
end

app/controllers/lits_controller.rb
class LitsController < ApplicationController

	def create 
	@fit = Fit.find(params[:fit_id])
	@lit = @fit.lits.create(params[:lit].permit(:exercise, :set, :reps, :weight, :time, :notes))
	@lit.save

	if @lit.save
			redirect_to fit_path(@fit)
	else
			render 'new'
	end
end

def edit 
	@fit = Fit.find(params[:fit_id])
 	@lit = @fit.lits.find(params[:id])
end 

	def update 
		@fit = Fit.find(params[:fit_id])
		@lit = @fit.lits.find(params[:id])
		
		if @lit.update(params[:lit].permit(:exercise, :set, :reps, :weight, :time, :notes))
			redirect_to fit_path(@fit)
		else 
			render 'edit'
		end 
	end 

	def destroy 
		@fit= Fit.find(params[:fit_id])
 		@lit = @fit.lits.find(params[:id])
 		@lit.destroy
 		redirect_to fit_path(@fit)
 	end


end

app/controllers/tits_controller.rb
class TitsController < ApplicationController

		def create 
	@fit = Fit.find(params[:fit_id])
	@tit = @fit.tits.create(params[:tit].permit(:exercise, :set, :reps, :weight, :time, :notes, :growthrate))
	@tit.save

	if @tit.save
			redirect_to fit_path(@fit)
	else
			render 'new'
	end
end


def edit 
	@fit = Fit.find(params[:fit_id])
 	@tit = @fit.tits.find(params[:id])
end 

	def update 
		@fit = Fit.find(params[:fit_id])
		@tit = @fit.tits.find(params[:id])
		
		if @tit.update(params[:tit].permit(:exercise, :set, :reps, :weight, :time, :notes, :growthrate))
			redirect_to fit_path(@fit)
		else 
			render 'edit'
		end 
	end 

	def destroy 
		@fit= Fit.find(params[:fit_id])
 		@tit = @fit.tits.find(params[:id])
 		@tit.destroy
 		redirect_to fit_path(@fit)
 	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bits_helper.rb
module BitsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/fits_helper.rb
module FitsHelper
end

app/helpers/kings_helper.rb
module KingsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/tits_helper.rb
module TitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/days/_form.html.erb
<%= simple_form_for(@day) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.date %></td>

        <td><%= link_to 'Show', day %></td>
        <td><%= link_to 'Edit', edit_day_path(day) %></td>
        <td><% link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Day', new_day_path, class: "btn btn-primary" %>

<br>
<%= will_paginate @days %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<%= link_to 'Days', days_path %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @day.date %>
</p>

<h2> Preperation for the day </h2><hr>


<%= render @day.things %> 


<h4> Add the most important thing</h4> 

	<%= render "things/form" %>
	

<hr>
<h2> Review of the day </h2>  <hr>
<%= render @day.kings %><br>

<%= render "kings/form" %>

  <%#inputs form (don’t copy the inputs form, that a description of what the code does.) %>


<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>

app/views/fits/_form.html.erb
<%= simple_form_for(@fit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :day %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fits/edit.html.erb
<h1>Editing fit</h1>

<%= render 'form' %>

<%= link_to 'Show', @fit %> |
<%= link_to 'Back', fits_path %>

app/views/fits/index.html.erb
<h1>Workout Date</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fits.each do |fit| %>
      <tr>
        <td><%= fit.day %></td>
        <td><%= link_to 'Show', fit %></td>
        <td><%= link_to 'Edit', edit_fit_path(fit) %></td>
        <td><% link_to 'Destroy', fit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Day', new_fit_path, class: "btn btn-primary" %>

<br>
<%= will_paginate @fits %>

app/views/fits/new.html.erb
<h1>New fit</h1>

<%= render 'form' %>

<%= link_to 'Back', fits_path %>

app/views/fits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @fit.day %>
</p>

<h3>Preview of the Workout</h3><hr><br>


	<%= render @fit.lits %><br>

	<%= render "lits/form" %><br>

<br>
<br>
<h3> Review of the workout </h3><hr>

<%= render @fit.tits %><br>

	<%= render "tits/form" %><br>



<%= link_to 'Edit', edit_fit_path(@fit) %> |
<%= link_to 'Back', fits_path %>


<%  "notes Add the output into tables where its the preview in one row, and the next row will be the review in the output. But its still two different forms that input the preview and the review from. Or two table of each, but the layout now is fucking terrible."   %>

app/views/tits/_form.html.erb
<%= form_for([@fit, @fit.tits.build]) do |f| %>
	<%= f.text_field :exercise, placeholder: "Exercise Name" %><br>
	<%= f.text_field :set, placeholder: "sets" %><br>
	<%= f.text_field :reps, placeholder: "reps" %><br>
	<%= f.text_field :weight, placeholder: "Weight" %><br>
	<%= f.text_field :time, placeholder: "How long did it take?" %><br>
	<%= f.text_area :notes, placeholder: "notes" %><br>
	<%= f.text_area :growthrate, placeholder: "What's the growth rate" %><br>
	<%= f.submit %>
<% end %>

app/views/tits/_tit.html.erb

<%= tit.exercise %>
<%= tit.set %>
<%= tit.reps %>
<%= tit.weight %>
<p><%= tit.time %></p>
<p><%= tit.notes %></p>
<p><%= tit.growthrate %></p>

<%= link_to 'Edit', edit_fit_tit_path(tit.fit, tit) %><br>

app/views/tits/edit.html.erb
<h1>Editing Important Thing</h1>     

<%= simple_form_for([@fit, @tit]) do |f| %> 
	<%= f.text_field :exercise, placeholder: "Exercise Name" %><br>
	<%= f.text_field :set, placeholder: "sets" %><br>
	<%= f.text_field :reps, placeholder: "reps" %><br>
	<%= f.text_field :weight, placeholder: "Weight" %><br>
	<%= f.text_field :time, placeholder: "How long should it take?" %><br>
	<%= f.text_area :notes, placeholder: "notes" %><br>
	<%= f.text_area :growthrate, placeholder: "Whats the growth rate?" %><br>
	<%= f.submit %>
<% end %>



<%= link_to 'Show', @fit %> |
<%= link_to 'Back', fits_path %>