config/routes.rb
Rails.application.routes.draw do



  resources :fits do 
  	 resources :lits 
     resources :tits
  	end 

  resources :days do 
    resources :things 
    resources :kings


  end 

 


  get 'welcomes/home'

  resources :teams do 
    resources :players 
  end 

  root "welcomes#home"
  
end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :things 
	has_many :kings
end

app/models/fit.rb
class Fit < ActiveRecord::Base
	has_many :lits
	has_many :tits
end

app/models/king.rb
class King < ActiveRecord::Base
  belongs_to :day
end

app/models/lit.rb
class Lit < ActiveRecord::Base
  belongs_to :fit
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :players
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :day
end

app/models/tit.rb
class Tit < ActiveRecord::Base
  belongs_to :fit
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [ :show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.paginate(:page => params[:page], :per_page => 8).order('created_at DESC')
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render :new }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bits_helper.rb
module BitsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/fits_helper.rb
module FitsHelper
end

app/helpers/kings_helper.rb
module KingsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/tits_helper.rb
module TitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_footer.html.erb
<br><br>
   <header class="navbar navbar-default" >
    <div class="container-fluid">
      <div class="footer-wrapper">
        <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- logo -->
      
      <p class="hidden-sm" style="margin-top:2.3em;"> &nbsp;&nbsp;</p>
    </div>
    <ul class="nav navbar-nav navbar-right">
      
      <li><a href="/terms-of-use">Terms &amp; Conditions</a></li>
      <li><a href="https://www.iubenda.com/privacy-policy/735465">Privacy Policy</a></li>
    </ul>
      </div>
    </div>
   <br>
   <br>
   <br>
  </header>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">
    <%=  link_to "Win Today", root_path %></div> <!-- win today div --> 
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to 'Football', teams_path %></li>
       <li><%= link_to 'Focus', days_path %></li>
            <li><%= link_to 'Workout', fits_path %></li>

            </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasyFootball</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	 

      <%= render 'layouts/header' %>  

	<div class="container">
		
       
          


		<%= yield %>


	</div> <!-- container --> 
<%= render 'layouts/footer' %>  


</body>
</html>